import './globals.css';
export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js'
};

export default function RootLayout({
    children
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className="p-14">
                <header>foo</header>
                <div className="p-10">{children}</div>
                <footer>bar</footer>
            </body>
        </html>
    );
}
