import { Oswald } from 'next/font/google';

import './globals.css';
import { getPosts } from '@/app/api';
import LinkComponent from '@/app/components/LinkComponent';

export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js'
};

const oswald = Oswald({ subsets: ['latin'] });

const RootLayout = async ({ children }: { children: React.ReactNode }) => {
    const { posts } = await getPosts();

    return (
        <html lang="en">
            <body className={`${oswald.className} container mx-auto`}>
                <div className="flex flex-col h-screen justify-between">
                    <header className="flex gap-4 justify-end pt-4">
                        <LinkComponent href="/">Home</LinkComponent>
                        <LinkComponent href="/posts">Posts</LinkComponent>
                        <LinkComponent href="/about">About</LinkComponent>
                    </header>
                    <main className="p-10 mb-auto">{children}</main>
                    <footer className="p-4 w-full text-center">bar</footer>
                </div>
            </body>
        </html>
    );
};

export default RootLayout;
