import { Ubuntu, Source_Code_Pro } from 'next/font/google';

import './globals.css';
import { getPosts } from '@/app/api';
import LinkComponent from '@/app/components/LinkComponent';
import Heading from '@/app/components/Heading';

export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js'
};

const font = Source_Code_Pro({
    subsets: ['latin'],
    weight: ['300', '400'],
    style: ['normal', 'italic']
});

const RootLayout = async ({ children }: { children: React.ReactNode }) => {
    // const { posts } = await getPosts();

    return (
        <html lang="en">
            <body className={`${font.className} container mx-auto font-light`}>
                <div className="flex flex-col h-screen justify-between">
                    <header className="flex justify-between items-center px-8 py-4">
                        <Heading level={1}>Mike Mitchell</Heading>
                        <div className="flex gap-4 justify-end pt-4">
                            <LinkComponent href="/">Home</LinkComponent>
                            <LinkComponent href="/photos">Photos</LinkComponent>
                            <LinkComponent href="/about">About</LinkComponent>
                        </div>
                    </header>
                    <main className="p-10 mb-auto">{children}</main>
                    <footer className="p-4 w-full text-center">bar</footer>
                </div>
            </body>
        </html>
    );
};

export default RootLayout;
